### ISSUE TITLE
js file

### ISSUE THREAD

**Issue by von1ok** [milindl/mafia-reloaded#5]
wont load in pale moon

**Comment by von1ok** [comment]
wont load in pale moon

**Comment by milindl** [comment]
I tested with Pale Moon 27.0.2

It seems to work fine when my port 8888 and 7000 are free.

Could you please post your details(version, screenshots, any error messages and stuff.)

Additionally, check [http://www.websocket.org/echo.html](http://www.websocket.org/echo.html) out once to test Websockets

**Comment by von1ok** [comment]
My bad i havent got python installed. Sorry. Too much like hard work for me. Thanks though
